baseURL = "https://sorokod.github.io/"
languageCode = "en-us"
title = "magpie"
theme = "beautifulhugo"

metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

publishDir = "../sorokod.github.io"

[Params]
  subtitle = "scavenger of shiny things"
  logo = "img/magpie.png"


[Author]
  name = "David Soroko"
  stackoverflow = "users/239101/david-soroko"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3    
